version: '3.8'

networks:
  shared-network:
    driver: bridge

services:

  dgraph-ratel:
    command: dgraph-ratel
    container_name: dgraph-ratel
    image: dgraph/ratel:v25.0.3
    ports:
      - 8000:8000
    networks:
      - shared-network
    healthcheck:
      test: ["CMD", "netstat", "-plnt", "|", "grep", ":8000"]
      interval: 10s
      start_period: 10s
      timeout: 5s
      retries: 3

  dgraph-zero:
    command: dgraph zero
    container_name: dgraph-zero
    image: dgraph/dgraph:v24.1.5
    networks:
      - shared-network

  dgraph-alpha:
    command: dgraph alpha --vmodule=server=3
    container_name: dgraph-alpha
    depends_on:
      dgraph-zero:
        condition: service_started
    image: dgraph/dgraph:v24.1.5
    networks:
      - shared-network

  travel-api:
    container_name: travel-api
    depends_on:
      dgraph-alpha:
        condition: service_started
    image: tullo/travel-api-amd64:1.0
    networks:
      - shared-network

  travel-ui:
    container_name: travel-ui
    depends_on:
      dgraph-alpha:
        condition: service_started
    image: tullo/travel-ui-amd64:1.0
    networks:
      - shared-network
